### ISSUE TITLE
Tracking node crashes

### ISSUE THREAD

**Issue by ahadviger** [HKUST-Aerial-Robotics/ESVO#4]
Hi,

Every time I run _esvo_core_ with either _indoor_flying1_edited.bag_ or _indoor_flying3_edited.bag_ downloaded from your page, I get the following error:
![image](https://user-images.githubusercontent.com/7397752/99706746-ce0a2180-2a9b-11eb-98a0-117581038a11.png)

The _esvo_time_surface_ node functions well and the map initializes properly. I didn't make any changes to the default parameters. Do you know what might be the problem?

Thanks,
Antea

**Comment by Ethan-Zhou** [comment]
Hi Antea,

Since no specific error information is seen from your snapshot, I would suggest you to slow down the rosbag and reduce the global timer rate accordingly. 

![ESVO_tip](https://user-images.githubusercontent.com/5391344/99745306-56c4a400-2b14-11eb-8166-34ae90aef5d5.png)

This can be done by, e.g., replace 0.5 -> 0.1, and 50 -> 10 accordingly in the above image (Setion 4 of the README).

If the pipeline runs normaly after that, it indicates that you need a powerful PC.

Cheers,

yi

**Comment by ahadviger** [comment]
Hi Ethan-Zhou,

Thanks for your reply. Unfortunately, changing the playback rate did not help. I also tried lowering the tracking rate in the config file, but with no success. I suspected that the stack memory might be too low, but increasing it did not make any change. I will continue debugging and let you know if anything helps.

Best,
Antea

**Comment by ahadviger** [comment]
I managed to solve this problem by adding `return 0;` to the end of the function `int RegProblemLM::df(const Eigen::Matrix<double,6,1>& x, Eigen::MatrixXd& fjac) const`, which was missing a return statement. Seems like this caused memory allocation problems. I will put up a pull request.

**Comment by Ethan-Zhou** [comment]
Hi @ahadviger 
Thanks for figuring out this mistake. It seems that we are free of this problem because of using a different compiler (I guess).
Anyway, I have pushed an update having this one fixed, together with another minor modification as documented there. So, you don't have to make a pull request on this.
Cheers,
yi
